---
- name: Deploy DevOps App to Tomcat
  hosts: localhost
  gather_facts: no
  vars:
    tomcat_ip: "172.31.26.51"
    war_file: "devops-app.war"

  tasks:
    - name: Maven Build
      command: mvn clean package
      args:
        chdir: "{{ playbook_dir }}"

    - name: Copy WAR file to Tomcat Server
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/target/{{ war_file }}"
        dest: "/opt/tomcat9/webapps/{{ war_file }}"
        remote_src: yes

    - name: Restart Tomcat
      ansible.builtin.shell:
        cmd: |
          ssh ec2-user@{{ tomcat_ip }} /opt/tomcat9/bin/shutdown.sh
          ssh ec2-user@{{ tomcat_ip }} /opt/tomcat9/bin/startup.sh
