---
- name: Deploy DevOps App
  hosts: tomcat_servers
  tasks:
    - name: Copy WAR file to Tomcat webapps directory
      copy:
        src: "target/devops-app.war"
        dest: "/opt/tomcat9/webapps/devops-app.war"
        remote_src: yes

    - name: Stop Tomcat
      become: yes
      service:
        name: tomcat
        state: stopped

    - name: Start Tomcat
      become: yes
      service:
        name: tomcat
        state: started
